name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Switch to working directory
        run: cd pokedex
      - name: Install modules
        run: npm install
      - name: Run tests
        run: npm run test
